/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import Project.koneksi;
import Project.InsertUpdateDelete;
import Project.Select;
import Project.Table;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author Hype
 */
public class CheckOut extends javax.swing.JFrame {

    private String String;

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(true);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(true);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        // Pemicu Tanggal Check Out
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hitungUlang(); // Panggil rumus hitung tanggal
            }
        });

        // Pemicu Jumlah Hari
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hitungDariHari(); // Panggil rumus hitung hari
            }
        });
    }
    int id = 0;
    String Query;
    String RoomType;
    String RoomNumber;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jLabel1.setText("Customer Checck Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 15, 245, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1191, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 77, 103, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 157, 245, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 195, 245, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Check IN date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 157, 245, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Check Out date (today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 157, 245, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 157, 245, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 195, 245, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 195, 245, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 195, 245, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PriceperDays");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 239, 245, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Number of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 239, 245, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 239, 245, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 239, 245, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 277, 245, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 277, 245, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 277, 245, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 277, 245, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 321, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Clear");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 321, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile Number", "Gender", "Email", "ID Member", "Address", "Check IN", "Room Number", "Room Type", "Price per days"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 354, 1191, 240));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("SELECT * FROM customer WHERE CheckOut IS NULL");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            while (rs.next()) {
                // --- 1. FORMAT HARGA ---
                double harga = 0;
                try {
                    // Kita ambil harga berdasarkan nama kolom 'pricePerDay' (atau sesuaikan dengan db kamu)
                    // Kalau bingung, pakai index 11 atau 13 (tergantung posisi di db), tapi amannya nama kolom.
                    String hargaText = rs.getString(11);
                    if (hargaText != null && !hargaText.isEmpty()) {
                        harga = Double.parseDouble(hargaText);
                    }
                } catch (Exception e) {
                }

                DecimalFormat dfCantik = new DecimalFormat("#,###");
                String hargaRapi = dfCantik.format(harga);

                // --- 2. MASUKKAN KE TABEL (URUTANNYA HARUS SESUAI JUDUL TABEL DI LAYAR) ---
                model.addRow(new Object[]{
                    rs.getString("id"), // Kolom 1: ID
                    rs.getString("name"), // Kolom 2: Name
                    rs.getString("mobileNumber"), // Kolom 3: Mobile Number
                    rs.getString("gender"), // Kolom 4: Gender
                    rs.getString("email"), // Kolom 5: Email
                    rs.getString("idProof"), // Kolom 6: ID Member
                    rs.getString("address"), // Kolom 7: Address
                    rs.getString("checkIn"), // Kolom 8: Check IN
                    rs.getString("roomNumber"), // Kolom 9: Room Number
                    rs.getString("roomType"), // Kolom 10: Room Type
                    hargaRapi // Kolom 11: Price (YANG SUDAH DIRAPIKAN)
                });
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String searchKey = jTextField1.getText();
        try {
            ResultSet rs = Select.getData("select * from customer where (RoomNumber='" + searchKey + "' OR Name='" + searchKey + "') and checkout is NULL");
            if (rs.next()) {
                jTextField1.setEnabled(false);
                id = rs.getInt(1);
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(8));
                jTextField5.setText(rs.getString(3));

                // --- BAGIAN 1: HARGA (Diambil & Diformat) ---
                // Kita simpan harga aslinya di variabel 'hargaMentah'
                double hargaMentah = rs.getDouble(11);

                // Format tampilan biar ada titiknya (Contoh: 550.000)
                DecimalFormat df = new DecimalFormat("#,###");
                jTextField6.setText(df.format(hargaMentah));

                // --- BAGIAN 2: HITUNG TANGGAL ---
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal = Calendar.getInstance();
                jTextField4.setText(myFormat.format(cal.getTime()));

                String dateBeforeString = rs.getString(8);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);

                long difference = dateAfter.getTime() - dateBefore.getTime();
                int noOfDayStay = (int) (difference / (1000 * 60 * 60 * 24));
                if (noOfDayStay == 0) {
                    noOfDayStay = 1;
                }

                jTextField7.setText(String.valueOf(noOfDayStay));

                // --- BAGIAN 3: PERBAIKAN TOTAL HARGA (PENTING!) ---
                // JANGAN ambil dari jTextField6.getText() karena itu ada titiknya (bikin error hitungan)
                // GUNAKAN 'hargaMentah' yang murni dari database
                double totalHitungan = noOfDayStay * hargaMentah; // Hitung pakai angka murni

                // Baru hasilnya diformat titiknya saat ditampilkan
                jTextField8.setText(df.format(totalHitungan));

                jTextField9.setText(rs.getString(6));
                RoomType = rs.getString(9);
            } else {
                JOptionPane.showMessageDialog(null, "Room Number is not Booked or does not exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void hitungUlang() {
        try {
            // 1. Ambil Data Harga & Tanggal
            String hargaText = jTextField6.getText().replace(".", "").replace(",", "");
            double harga = Double.parseDouble(hargaText);
            String checkIn = jTextField3.getText();
            String checkOut = jTextField4.getText(); // Ini yang kamu edit

            // 2. Hitung Durasi Hari (Berdasarkan Tanggal Check Out Baru)
            java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("yyyy/MM/dd");
            java.util.Date d1 = format.parse(checkIn);
            java.util.Date d2 = format.parse(checkOut);

            long diff = d2.getTime() - d1.getTime();
            int hari = (int) (diff / (1000 * 60 * 60 * 24));

            if (hari <= 0) {
                hari = 1;
            } // Minimal 1 hari

            // 3. Update Kolom Jumlah Hari & Total
            jTextField7.setText(String.valueOf(hari)); // Update Number of Days
            jTextField8.setText(String.valueOf(hari * harga)); // Update Total Amount
            double total = hari * harga;
            DecimalFormat df = new DecimalFormat("#,###"); // Format polos
            jTextField8.setText(df.format(total));
        } catch (Exception e) {
            // Error diamkan saja (misal user belum selesai ngetik tanggal)
        }
    }

    // Method khusus jika kamu mengedit Angka Hari langsung (bukan tanggal)
    public void hitungDariHari() {
        try {
            int hari = Integer.parseInt(jTextField7.getText());
            float harga = Float.parseFloat(jTextField6.getText());
            double total = hari * harga;
            DecimalFormat df = new DecimalFormat("#,###");
            jTextField8.setText(df.format(total));
            // Update Total

        } catch (Exception e) {
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = jTextField2.getText();
        String MobileNumber = jTextField5.getText();
        String Email = jTextField9.getText();
        String CheckOut = jTextField4.getText();
        String NumberOfDaysStay = jTextField7.getText();
        String TotalAmount = jTextField8.getText().replace(".", "").replace(",", "");
        RoomNumber = jTextField1.getText();
        String realIDMember = "-"; // Default kalau kosong
        try {
            // Kita cari data ID Member (IDProof) berdasarkan id transaksi/kamar ini
            java.sql.ResultSet rsMember = Project.Select.getData("SELECT * FROM customer WHERE id='" + id + "'");
            if (rsMember.next()) {
                realIDMember = rsMember.getString("IDProof"); // Pastikan nama kolom di databasemu 'IDProof'
            }
        } catch (Exception e) {
        }

        // 1. Update Data Customer (Checkout Date, Lama Inap, Total Harga)
        Query = "update customer set NumberOfDaysStay='" + NumberOfDaysStay + "',TotalAmount='" + TotalAmount + "',CheckOut='" + CheckOut + "'where id='" + id + "'";
        InsertUpdateDelete.setData(Query, "");

        // ========================================================================
        // LOGIKA BARU: TANYA STATUS KAMAR (Available / Maintenance)
        // ========================================================================
        String statusKamarBaru = "Available"; // Default

        int jawaban = javax.swing.JOptionPane.showConfirmDialog(null,
                "Apakah ada kerusakan atau keluhan di kamar ini?",
                "Cek Kondisi Kamar",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (jawaban == javax.swing.JOptionPane.YES_OPTION) {
            // Jika diklik YES (Ada kerusakan) -> Jadi Maintenance
            statusKamarBaru = "Maintenance";
        } else {
            // Jika diklik NO (Aman) -> Jadi Available
            statusKamarBaru = "Available";
        }

        // 2. Update Status Kamar sesuai jawaban tadi
        Query = "update room set Status='" + statusKamarBaru + "' where RoomNumber='" + RoomNumber + "'";
        InsertUpdateDelete.setData(Query, "");
        // ========================================================================

        // 3. Proses Cetak PDF (Sama seperti code asli Anda)
        // ... (Kode update database / status kamar di atas biarkan saja) ...
        // --- MULAI KODE CETAK BILL ---
        // ... (Kode update database di atas biarkan saja) ...
        // --- SETUP FILE & FOLDER ---
        // ... (Kode update database di bagian atas biarkan saja) ...
        String id = jTextField1.getText();
        String path = "C:\\Bill\\";
        String namaFile = id + ".pdf";
        String fullPath = path + namaFile;
        String pathLogo = path + "logo.png";

        // Ambil nama user
        String userLogin = Login.userAktif;
        if (userLogin == null || userLogin.isEmpty()) {
            userLogin = "Admin";
        }

        File dir = new File(path);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        com.lowagie.text.Document doc = new com.lowagie.text.Document();

        try {
            com.lowagie.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream(fullPath));
            doc.open();

            // --- FONT SETTING ---
            com.lowagie.text.Font headerFont = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 12);
            com.lowagie.text.Font normalFont = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 10);
            com.lowagie.text.Font smallFont = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 8);

            // =====================================================================
            // A. HEADER (LOGO TENGAH + ALAMAT TENGAH)
            // =====================================================================
            try {
                com.lowagie.text.Image logoImg = com.lowagie.text.Image.getInstance(pathLogo);
                logoImg.scaleToFit(80, 80);
                logoImg.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                doc.add(logoImg);
            } catch (Exception e) {
            }

            String isiAlamat = "Jl. Kramat Raya No. 81, Jakarta 10450, Indonesia\n"
                    + "Telp: (021) 390 3030 | Fax: (021) 390 3388\n"
                    + "Email: reservation@acacia-hotel.com";
            com.lowagie.text.Paragraph pAlamat = new com.lowagie.text.Paragraph(isiAlamat, normalFont);
            pAlamat.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            doc.add(pAlamat);

            doc.add(new com.lowagie.text.Paragraph("\n"));
            com.lowagie.text.Paragraph garis = new com.lowagie.text.Paragraph("--------------------------------------------------------------------------------------------------------");
            garis.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            doc.add(garis);
            doc.add(new com.lowagie.text.Paragraph("\n"));

            // =====================================================================
            // B. JUDUL BILL
            // =====================================================================
            com.lowagie.text.Paragraph judulBill = new com.lowagie.text.Paragraph("GUEST BILL / INVOICE", headerFont);
            judulBill.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            doc.add(judulBill);
            doc.add(new com.lowagie.text.Paragraph("\n"));

            // =====================================================================
            // C. INFORMASI CUSTOMER
            // =====================================================================
            com.lowagie.text.pdf.PdfPTable infoTable = new com.lowagie.text.pdf.PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setWidths(new float[]{1f, 2f});

            addInfoRow(infoTable, "ID Member", ": " + realIDMember, headerFont, normalFont);
            addInfoRow(infoTable, "Guest Name", ": " + name, headerFont, normalFont);
            addInfoRow(infoTable, "Mobile No", ": " + MobileNumber, headerFont, normalFont);
            addInfoRow(infoTable, "Email", ": " + Email, headerFont, normalFont);
            addInfoRow(infoTable, " ", " ", normalFont, normalFont);

            addInfoRow(infoTable, "Room Number", ": " + jTextField1.getText(), headerFont, normalFont);
            addInfoRow(infoTable, "Room Type", ": " + RoomType, headerFont, normalFont);
            addInfoRow(infoTable, "Rate / Night", ": " + jTextField6.getText(), headerFont, normalFont);

            doc.add(infoTable);
            doc.add(new com.lowagie.text.Paragraph("\n"));

            // =====================================================================
            // D. TABEL RINCIAN BIAYA (DENGAN FORMAT TITIK)
            // =====================================================================
            com.lowagie.text.pdf.PdfPTable tableBiaya = new com.lowagie.text.pdf.PdfPTable(4);
            tableBiaya.setWidthPercentage(100);
            tableBiaya.setWidths(new float[]{3f, 3f, 2f, 3f});

            // Header Tabel
            addHeaderCell(tableBiaya, "Check In");
            addHeaderCell(tableBiaya, "Check Out");
            addHeaderCell(tableBiaya, "Days");
            addHeaderCell(tableBiaya, "Total Amount");

            // Isi Data
            tableBiaya.addCell(new com.lowagie.text.Paragraph(jTextField3.getText(), normalFont));
            tableBiaya.addCell(new com.lowagie.text.Paragraph(CheckOut, normalFont));
            tableBiaya.addCell(new com.lowagie.text.Paragraph(NumberOfDaysStay, normalFont));

            // --- PERBAIKAN DI SINI ---
            // 1. Siapkan Format
            java.text.DecimalFormat dfPDF = new java.text.DecimalFormat("#,###");

            // 2. Ambil angka total, bersihkan titik lama, jadikan Double
            double totalNilai = Double.parseDouble(jTextField8.getText().replace(".", "").replace(",", ""));

            // 3. Format ulang biar cantik (1200000 -> 1.200.000)
            String totalCantik = dfPDF.format(totalNilai);

            // 4. Masukkan ke Cell (Rata Kanan)
            com.lowagie.text.pdf.PdfPCell cellTotal = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(totalCantik, headerFont));
            cellTotal.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_RIGHT);
            tableBiaya.addCell(cellTotal);

            doc.add(tableBiaya);
            doc.add(new com.lowagie.text.Paragraph("\n"));

            // =====================================================================
            // E. NAMA RESEPSIONIS (TANGGAL SESUAI CHECKOUT)
            // =====================================================================
            // --- BAGIAN INI YANG DIUBAH ---
            // Menggunakan variabel 'CheckOut' bukannya 'new Date()'
            String teksFooter = "Jakarta, " + CheckOut + "\n"
                    + "Receptionist: " + userLogin;

            com.lowagie.text.Paragraph pFooter = new com.lowagie.text.Paragraph(teksFooter, smallFont);
            pFooter.setAlignment(com.lowagie.text.Element.ALIGN_RIGHT); // Rata Kanan
            doc.add(pFooter);
            // ------------------------------

            // =====================================================================
            // F. FOOTER TERIMAKASIH
            // =====================================================================
            doc.add(new com.lowagie.text.Paragraph("\n"));
            com.lowagie.text.Paragraph footer = new com.lowagie.text.Paragraph("Thank you for choosing The Acacia Hotel Jakarta.", smallFont);
            footer.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            doc.add(footer);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Mencetak: " + e);
        }

        doc.close();

        // Buka File Otomatis
        try {
            if (new File(fullPath).exists()) {
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + fullPath);
            }
        } catch (Exception e) {
        }// ... (Kode update database di atas biarkan saja) ...

        // --- SETUP FILE & FOLDER ---
        setVisible(false);
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        javax.swing.table.TableModel model = jTable1.getModel();

        // 2. Ambil CUKUP SATU DATA SAJA: Room Number (Kolom ke-8)
        // (Pastikan urutan kolom di tabelmu: ID=0, ... RoomNumber=8)
        String roomNo = model.getValueAt(index, 8).toString();
        // 3. Masukkan ke Kotak Search
        jTextField1.setText(roomNo);
        String name = model.getValueAt(index, 1).toString();
        jTextField2.setText(name);
        // 4. PANGGIL TOMBOL SEARCH SECARA OTOMATIS
        // Ini kuncinya! Komputer akan "memencet" tombol Search untukmu.
        // Jadi ID, Nama, Harga, Tanggal, Total semua akan terisi otomatis oleh tombol Search.
        jButton2ActionPerformed(null);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
// --- TEMPEL KODE INI DI BAGIAN BAWAH FILE (DI LUAR TOMBOL) ---

    public void addInfoRow(PdfPTable table, String label, String value, com.lowagie.text.Font fontLabel, com.lowagie.text.Font fontValue) {
        PdfPCell c1 = new PdfPCell(new Paragraph(label, fontLabel));
        c1.setBorder(PdfPCell.NO_BORDER);
        table.addCell(c1);

        PdfPCell c2 = new PdfPCell(new Paragraph(value, fontValue));
        c2.setBorder(PdfPCell.NO_BORDER);
        table.addCell(c2);
    }

    public void addHeaderCell(PdfPTable table, String title) {
        com.lowagie.text.Font fontHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
        PdfPCell cell = new PdfPCell(new Paragraph(title, fontHeader));
        cell.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(5);
        table.addCell(cell);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
