
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Hype
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    boolean isAdmin = false;

    public Home() {
        initComponents();

    }

    public void enableAdminAccess() {
        isAdmin = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 0, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1790, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hotel ikon/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();
        popup.setBackground(java.awt.Color.WHITE); // Warna dasar menu

        // 2. Buat Item-Item Menunya (Ini pengganti tombol-tombol lama)
        javax.swing.JMenuItem itemAdmin = new javax.swing.JMenuItem("Admin");
        javax.swing.JMenuItem itemRoom = new javax.swing.JMenuItem("Manage Room");
        javax.swing.JMenuItem itemCheckIn = new javax.swing.JMenuItem("Customer Check In");
        javax.swing.JMenuItem itemCheckOut = new javax.swing.JMenuItem("Customer Check Out");
        javax.swing.JMenuItem itemBill = new javax.swing.JMenuItem("Invoicedata");

        java.awt.Font fontMenu = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
        java.awt.Color merah = java.awt.Color.RED;

        // Fungsi kecil untuk mendandani item (biar kodenya tidak panjang berulang-ulang)
        styleItem(itemAdmin, "/Image/admin.png", fontMenu, merah);
        styleItem(itemRoom, "/Image/manage room.png", fontMenu, merah);
        styleItem(itemCheckIn, "/Image/Customer Registration & Check IN.png", fontMenu, merah);
        styleItem(itemCheckOut, "/Image/Customer Check Out.png", fontMenu, merah);
        styleItem(itemBill, "/Image/Customer Details Bill.png", fontMenu, merah);

        // 4. Beri "Nyawa" (Fungsi Pindah Halaman)
        itemAdmin.addActionListener(e -> {

            new AdminHome().setVisible(true);
        });

        itemRoom.addActionListener(e -> {

            new ManageRoom().setVisible(true);
        });

        itemCheckIn.addActionListener(e -> {

            new CheckIN().setVisible(true);
        });

        itemCheckOut.addActionListener(e -> {

            new CheckOut().setVisible(true);
        });

        itemBill.addActionListener(e -> {

            new InvoiceData().setVisible(true);
        });

        // 5. Masukkan Item ke dalam Popup
        if (isAdmin == true) {
            popup.add(itemAdmin);
            popup.add(itemRoom);
        }
        popup.add(itemCheckIn);
        popup.add(itemCheckOut);
        popup.add(itemBill);

        popup.setPreferredSize(new java.awt.Dimension(jButton1.getWidth(), popup.getPreferredSize().height));

        // 6. TAMPILKAN POPUP DI BAWAH TOMBOL
        // (Tombol yang diklik adalah 'jButtonMenu', sesuaikan nama variabel tombolmu)
        popup.show(jButton1, 0, jButton1.getHeight());
    }

// --- FUNGSI TAMBAHAN (Letakkan di luar method actionPerformed, tapi di dalam class) ---
// Gunanya biar kodingan di atas rapi
    private void styleItem(javax.swing.JMenuItem item, String pathGambar, java.awt.Font font, java.awt.Color warna) {
        item.setFont(font);
        item.setForeground(warna);
        item.setBackground(java.awt.Color.WHITE);
        try {
            item.setIcon(new javax.swing.ImageIcon(getClass().getResource(pathGambar)));
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close this page?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
