
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
import Project.*;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Hype
 */
public class InvoiceData extends javax.swing.JFrame {

    public String jenisLaporan = "Laporan Transaksi";

    /**
     * Creates new form CustomerBill
     */
    public InvoiceData() {
        initComponents();
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        jTextField1.setText(myFormat.format(cal.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButtonPilihLaporan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Customer Details Bill.png"))); // NOI18N
        jLabel1.setText("InvoiceData");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 19, 164, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile Number", "Address", "Gender", "Email", "ID Member", "CheckIN", "Room Type", "Room Number", "Price ", "DayStay", "CheckOut", "Total Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 177, 1192, 350));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 550, -1, -1));

        jButtonPilihLaporan.setBackground(new java.awt.Color(255, 51, 51));
        jButtonPilihLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPilihLaporan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPilihLaporan.setText("Laporan");
        jButtonPilihLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPilihLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("SELECT *FROM customer WHERE CheckOut IS NULL");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                // --- FORMAT HARGA ---
                DecimalFormat df = new DecimalFormat("#,###");

                double price = 0;
                try {
                    price = rs.getDouble(11);
                } catch (Exception e) {
                } // Kolom 11 = Price

                double total = 0;
                try {
                    total = rs.getDouble(14);
                } catch (Exception e) {
                }
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13), rs.getString(14)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField1.getText();

        // PENTING: Kita ambil model dari tabel GUI yang sudah ada
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DecimalFormat df = new DecimalFormat("#,###");

        try {
            String sql = "";

            // ====================================================================
            // 1. LAPORAN TRANSAKSI (Kembali ke Format Asli GUI)
            // ====================================================================
            if (jenisLaporan.equals("Laporan Transaksi")) {

                // 1. Matikan Fit Screen (Wajib biar bisa scroll)
                jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

                // 2. Reset Judul
                model.setColumnIdentifiers(new String[]{
                    "ID", "Name", "Mobile Number", "Address", "Gender", "Email", "ID Member",
                    "CheckIN", "Room Type", "Room No", "Price ", "DayStay", "CheckOut", "TotalAmount"
                });

                // 3. ATUR UKURAN SATU PER SATU BIAR PAS (TIDAK KEKECILAN/KELEBARAN)
                javax.swing.table.TableColumnModel colModel = jTable1.getColumnModel();

                colModel.getColumn(0).setPreferredWidth(40);  // ID (Kecil aja)
                colModel.getColumn(1).setPreferredWidth(80); // Name (Sedang)
                colModel.getColumn(2).setPreferredWidth(105); // Mobile (Sedang)
                colModel.getColumn(3).setPreferredWidth(95); // Address (LEBAR)
                colModel.getColumn(4).setPreferredWidth(70);  // Gender (Kecil)
                colModel.getColumn(5).setPreferredWidth(130); // Email (Agak Lebar)
                colModel.getColumn(6).setPreferredWidth(80);  // ID Member
                colModel.getColumn(7).setPreferredWidth(90);  // CheckIN
                colModel.getColumn(8).setPreferredWidth(100); // Room Type
                colModel.getColumn(9).setPreferredWidth(70);  // Room No
                colModel.getColumn(10).setPreferredWidth(90); // Price
                colModel.getColumn(11).setPreferredWidth(60); // DayStay (Kecil)
                colModel.getColumn(12).setPreferredWidth(90); // CheckOut
                colModel.getColumn(13).setPreferredWidth(80); // Total

                // 4. Isi Data
                model.setRowCount(0);
                sql = "SELECT * FROM customer WHERE CheckOut IS NOT NULL AND (Name LIKE '%" + keyword + "%' OR RoomNumber LIKE '%" + keyword + "%' OR CheckIN LIKE '%" + keyword + "%' OR CheckOut LIKE '%" + keyword + "%')";
                java.sql.ResultSet rs = Project.Select.getData(sql);

                while (rs.next()) {
                    double price = rs.getDouble("Price");
                    double total = rs.getDouble("TotalAmount");
                    model.addRow(new Object[]{
                        rs.getString("id"), rs.getString("Name"), rs.getString("MobileNumber"),
                        rs.getString("Address"), rs.getString("Gender"), rs.getString("Email"),
                        rs.getString("IDProof"), rs.getString("CheckIN"), rs.getString("RoomType"),
                        rs.getString("RoomNumber"), df.format(price), rs.getString("NumberOfDaysStay"),
                        rs.getString("CheckOut"), df.format(total)
                    });
                }
            } // ====================================================================
            // 2. LAPORAN KEUANGAN (FIT SCREEN - RAPI SATU LAYAR)
            // ====================================================================
            else if (jenisLaporan.equals("Laporan Keuangan")) {
                // Hidupkan "Fit to Screen"
                jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

                model.setColumnIdentifiers(new String[]{"ID", "Name", "Check IN", "Check Out", "Total Amount"});
                model.setRowCount(0);

                sql = "SELECT * FROM customer WHERE CheckOut IS NOT NULL AND (Name LIKE '%" + keyword + "%' OR RoomNumber LIKE '%" + keyword + "%' OR CheckIN LIKE '%" + keyword + "%' OR CheckOut LIKE '%" + keyword + "%')";
                java.sql.ResultSet rs = Project.Select.getData(sql);

                while (rs.next()) {
                    double total = rs.getDouble("TotalAmount");
                    model.addRow(new Object[]{rs.getString("id"), rs.getString("Name"), rs.getString("CheckIN"), rs.getString("CheckOut"), df.format(total)});
                }
            } // ====================================================================
            // 3. LAPORAN DATA KAMAR
            // ====================================================================
            else if (jenisLaporan.equals("Laporan Data Kamar")) {
                jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

                // Deteksi apakah user mengetik Tanggal?
                boolean cariTanggal = keyword.contains("/") || keyword.contains("-");

                if (cariTanggal) {
                    // --- KONDISI A: PENCARIAN TANGGAL (5 KOLOM) ---
                    // Header Tabel
                    model.setColumnIdentifiers(new String[]{"No Kamar", "Tipe Kamar", "Harga", "Status Saat Ini", "Tgl Sewa"});
                    model.setRowCount(0);

                    // QUERY (5 Kolom): Ambil CheckIN dari tabel customer
                    sql = "SELECT r.RoomNumber, r.RoomType, r.Price, r.Status, c.CheckIN "
                            + "FROM room r JOIN customer c ON r.RoomNumber = c.RoomNumber "
                            + "WHERE c.CheckIN LIKE '%" + keyword + "%' "
                            + "ORDER BY r.RoomNumber ASC";

                    java.sql.ResultSet rs = Project.Select.getData(sql);
                    while (rs.next()) {
                        double price = rs.getDouble(3);
                        // Masukkan 5 Data ke Tabel
                        model.addRow(new Object[]{
                            rs.getString(1), // RoomNumber
                            rs.getString(2), // RoomType
                            df.format(price), // Price
                            rs.getString(4), // Status
                            rs.getString(5) // CheckIN
                        });
                    }

                } else {
                    // --- KONDISI B: PENCARIAN BIASA (4 KOLOM) ---
                    // Header Tabel
                    model.setColumnIdentifiers(new String[]{"No Kamar", "Tipe Kamar", "Harga", "Status Saat Ini"});
                    model.setRowCount(0);

                    // QUERY (4 Kolom): Ambil dari tabel room saja
                    sql = "SELECT RoomNumber, RoomType, Price, Status FROM room "
                            + "WHERE RoomNumber LIKE '%" + keyword + "%' "
                            + "OR RoomType LIKE '%" + keyword + "%' "
                            + "OR Status LIKE '%" + keyword + "%' "
                            + "ORDER BY RoomNumber ASC";

                    java.sql.ResultSet rs = Project.Select.getData(sql);
                    while (rs.next()) {
                        double price = rs.getDouble(3);
                        // Masukkan 4 Data ke Tabel
                        model.addRow(new Object[]{
                            rs.getString(1), // RoomNumber
                            rs.getString(2), // RoomType
                            df.format(price), // Price
                            rs.getString(4) // Status
                        });
                    }
                }
            } // ====================================================================
            // 4. LAPORAN DATA PELANGGAN
            // ====================================================================
            else if (jenisLaporan.equals("Laporan Data Pelanggan")) {
                jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
                model.setColumnIdentifiers(new String[]{"Name", "No HP", "Email", "Address", "Gender", "ID Member"});
                model.setRowCount(0);

                sql = "SELECT * FROM customer WHERE CheckOut IS NOT NULL AND (Name LIKE '%" + keyword + "%' OR RoomNumber LIKE '%" + keyword + "%' OR CheckIN LIKE '%" + keyword + "%' OR CheckOut LIKE '%" + keyword + "%')";
                java.sql.ResultSet rs = Project.Select.getData(sql);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("Name"), rs.getString("MobileNumber"), rs.getString("Email"),
                        rs.getString("Address"), rs.getString("Gender"), rs.getString("IDProof")
                    });
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error Database: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        try {
            if (new File("C:\\Bill\\" + id + ".pdf").exists()) {
                Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler C:\\Bill\\" + id + ".pdf");
            } else {
                JOptionPane.showMessageDialog(null, "File is not exists");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // 1. Ambil teks dari input field                                         
        // 1. Setup Nama File & Folder
        String inputTanggal = jTextField1.getText();
        String keywordAman = inputTanggal.replace("/", "-").replace("\\", "-").replace(":", "");
        if (keywordAman.isEmpty()) {
            keywordAman = "SemuaData";
        }
String folderPath = "C:\\laporanrekap\\";
String namaFile = jenisLaporan + "_" + keywordAman + ".pdf";
String fullPath = folderPath + namaFile;

java.io.File dir = new java.io.File(folderPath);
if (!dir.exists()) { dir.mkdirs(); }

try {
    String userLogin = Login.userAktif; 
    String pathLogo = "C:\\laporanrekap\\logo.png"; 

    // 1. SETUP KERTAS
    // Margin Bawah 30f (Memberi ruang sedikit agar tanda tangan tidak terlalu mepet bawah)
    com.lowagie.text.Document doc = new com.lowagie.text.Document(com.lowagie.text.PageSize.A4, 10f, 10f, 20f, 30f);
    com.lowagie.text.pdf.PdfWriter writer = com.lowagie.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream(fullPath));

    doc.open();
    int jumlahKolom = jTable1.getColumnCount();
    
    com.lowagie.text.Font fontPage = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 8);

    // =========================================================================
    // SATU LOGIKA UNTUK SEMUA LAPORAN (AGAR KONSISTEN)
    // =========================================================================
    int barisPerHalaman = 25; 
    int totalBaris = jTable1.getRowCount();
    int jumlahHalaman = (int) Math.ceil((double) totalBaris / barisPerHalaman);
    double totalPendapatan = 0;
    float sizeFont = jenisLaporan.equals("Laporan Transaksi") ? 6f : 8f;

    // Jaga-jaga kalau tabel kosong, tetap print 1 halaman
    if (jumlahHalaman == 0) jumlahHalaman = 1;

    for (int hal = 0; hal < jumlahHalaman; hal++) {
        if (hal > 0) doc.newPage(); // Pindah kertas untuk halaman selanjutnya

        // --- A. LOGO ---
        try {
            com.lowagie.text.Image logoImg = com.lowagie.text.Image.getInstance(pathLogo);
            logoImg.scaleToFit(60, 60); 
            logoImg.setAlignment(com.lowagie.text.Image.ALIGN_CENTER); 
            doc.add(logoImg);
        } catch (Exception e) {}

        // --- B. JUDUL ---
        com.lowagie.text.Font fontJudul = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 10);
        com.lowagie.text.Paragraph pJudul = new com.lowagie.text.Paragraph(jenisLaporan.toUpperCase(), fontJudul);
        pJudul.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
        doc.add(pJudul);

        com.lowagie.text.Font fontPer = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 8);
        com.lowagie.text.Paragraph pPer = new com.lowagie.text.Paragraph("Periode: " + inputTanggal, fontPer);
        pPer.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
        pPer.setSpacingAfter(5f); 
        doc.add(pPer);

        // --- C. TABEL ---
        com.lowagie.text.pdf.PdfPTable pdfTable = new com.lowagie.text.pdf.PdfPTable(jumlahKolom);
        pdfTable.setWidthPercentage(100);
        
        // Setting Lebar Kolom (Otomatis deteksi 4 atau 5 kolom)
        try {
            if (jenisLaporan.equals("Laporan Data Kamar")) {
                if (jumlahKolom == 4) {
                    pdfTable.setWidths(new float[]{2f, 4f, 3f, 4f}); // Data Kamar (4 Kolom)
                } else {
                    pdfTable.setWidths(new float[]{2f, 3f, 3f, 3f, 4f}); // Data Kamar (5 Kolom)
                }
            } 
            else if (jenisLaporan.equals("Laporan Transaksi")) {
                // Sesuaikan jika kolom transaksi kamu banyak
                float[] widths = { 1.5f, 3f, 2.5f, 3.5f, 1.5f, 4f, 1.5f, 2.5f, 2.5f, 1.5f, 3f, 1.2f, 2.5f, 3.5f };
                pdfTable.setWidths(widths); 
            } 
            else if (jenisLaporan.equals("Laporan Keuangan")) pdfTable.setWidths(new float[]{2f, 5f, 4f, 4f, 4f}); 
            else if (jenisLaporan.equals("Laporan Data Pelanggan")) pdfTable.setWidths(new float[]{4f, 3f, 3f, 3f, 4f, 4f, 2f, 3f}); 
        } catch(Exception e) {}

        // Header Tabel
        com.lowagie.text.Font fontHeader = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, sizeFont);
        for (int i = 0; i < jumlahKolom; i++) {
            com.lowagie.text.pdf.PdfPCell cell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(jTable1.getColumnName(i), fontHeader));
            cell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            cell.setVerticalAlignment(com.lowagie.text.Element.ALIGN_MIDDLE);
            cell.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
            cell.setPadding(2);
            pdfTable.addCell(cell);
        }

        // Isi Data Tabel
        int startRow = hal * barisPerHalaman;
        int endRow = Math.min(startRow + barisPerHalaman, totalBaris);
        com.lowagie.text.Font fontData = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, sizeFont);
        
        for (int i = startRow; i < endRow; i++) {
            if(jenisLaporan.equals("Laporan Keuangan")) {
                try {
                    String valStr = jTable1.getValueAt(i, 4).toString(); 
                    if(valStr != null && !valStr.isEmpty()) {
                        String angkaBersih = valStr.replaceAll("[^0-9]", ""); 
                        totalPendapatan += Double.parseDouble(angkaBersih);
                    }
                } catch (Exception e) {}
            }
            for (int cols = 0; cols < jumlahKolom; cols++) {
                Object val = jTable1.getValueAt(i, cols);
                com.lowagie.text.pdf.PdfPCell cell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(val==null?"":val.toString(), fontData));
                cell.setVerticalAlignment(com.lowagie.text.Element.ALIGN_MIDDLE);
                cell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER); 
                cell.setPadding(2);
                pdfTable.addCell(cell);
            }
        }

        // Baris Total (Khusus Keuangan di halaman terakhir)
        if (hal == jumlahHalaman - 1 && jenisLaporan.equals("Laporan Keuangan")) {
             pdfTable.addCell(""); pdfTable.addCell(""); pdfTable.addCell(""); 
             com.lowagie.text.pdf.PdfPCell cL = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph("TOTAL", fontHeader));
             cL.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_RIGHT);
             pdfTable.addCell(cL);
             String tF = String.format("%,.0f", totalPendapatan);
             com.lowagie.text.pdf.PdfPCell cT = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph("Rp " + tF, fontHeader));
             cT.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
             pdfTable.addCell(cT);
        }
        
        doc.add(pdfTable);
        
        // --- D. NOMOR HALAMAN (DI BAWAH TABEL LANGSUNG) ---
        // Posisinya tepat setelah 'doc.add(pdfTable)'
        com.lowagie.text.Paragraph pPage = new com.lowagie.text.Paragraph("Halaman " + (hal + 1), fontPage);
        pPage.setAlignment(com.lowagie.text.Element.ALIGN_RIGHT); 
        pPage.setSpacingBefore(5f); // Jarak 5 pixel dari pantat tabel
        doc.add(pPage);
        // --------------------------------------------------

        // --- E. TANDA TANGAN ---
        buatTandaTanganBaru(doc, userLogin);
    } 

    doc.close(); 
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(null, "Error PDF: " + e.getMessage());
}

// Konfirmasi Buka File
int a = javax.swing.JOptionPane.showConfirmDialog(null, "PDF Berhasil Disimpan.\nBuka sekarang?", "Sukses", javax.swing.JOptionPane.YES_NO_OPTION);
if (a == javax.swing.JOptionPane.YES_OPTION) {
    try {
        if (new java.io.File(fullPath).exists()) {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + fullPath);
        }
    } catch (Exception e) {}
}
    }//GEN-LAST:event_jButton3ActionPerformed
// Fungsi Tanda Tangan (Letakkan di luar tombol, tapi di dalam class)

    private void buatTandaTanganBaru(com.lowagie.text.Document doc, String namaUser) throws Exception {
       com.lowagie.text.pdf.PdfPTable ttdTable = new com.lowagie.text.pdf.PdfPTable(1);
 ttdTable.setWidthPercentage(30);
 ttdTable.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_RIGHT);

 com.lowagie.text.pdf.PdfPCell ttdCell = new com.lowagie.text.pdf.PdfPCell();
 ttdCell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
 ttdCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);

 // --- PERUBAHAN DISINI (Tambah EEEE biar muncul Hari) ---
 java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("EEEE, dd MMMM yyyy", new java.util.Locale("id", "ID"));
 String tanggalCetak = sdf.format(new java.util.Date());
 // -------------------------------------------------------

 com.lowagie.text.Font fontKecil = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 8);
 // com.lowagie.text.Font fontTebal = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 8); // Opsional kalau mau dipake

 ttdCell.addElement(new com.lowagie.text.Paragraph("Jakarta, " + tanggalCetak, fontKecil));
 ttdCell.addElement(new com.lowagie.text.Paragraph("Penanggung Jawab,", fontKecil));
 ttdCell.addElement(new com.lowagie.text.Paragraph("\n\n\n"));
 ttdCell.addElement(new com.lowagie.text.Paragraph("(  " + namaUser.toUpperCase() + "  )", fontKecil));

 ttdTable.addCell(ttdCell);
 doc.add(ttdTable);
    }
    private void jButtonPilihLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihLaporanActionPerformed
        // TODO add your handling code here:
        javax.swing.JPopupMenu popup = new javax.swing.JPopupMenu();

        // 2. Buat Item Menu
        javax.swing.JMenuItem item1 = new javax.swing.JMenuItem("Laporan Transaksi");
        javax.swing.JMenuItem item2 = new javax.swing.JMenuItem("Laporan Keuangan");
        javax.swing.JMenuItem item3 = new javax.swing.JMenuItem("Laporan Data Kamar");
        javax.swing.JMenuItem item4 = new javax.swing.JMenuItem("Laporan Data Pelanggan");

        // 3. Aksi Jika Menu 'Laporan Transaksi' Diklik
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaporan = "Laporan Transaksi";          // Simpan ke variabel
                jButtonPilihLaporan.setText("Transaksi ▼");  // Ganti tulisan tombol
            }
        });

        // 4. Aksi Jika Menu 'Laporan Keuangan' Diklik
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaporan = "Laporan Keuangan";
                jButtonPilihLaporan.setText("Keuangan ▼");
            }
        });

        // 5. Aksi Jika Menu 'Data Kamar' Diklik
        item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaporan = "Laporan Data Kamar";
                jButtonPilihLaporan.setText("Data Kamar ▼");
            }
        });

        // 6. Aksi Jika Menu 'Data Pelanggan' Diklik
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLaporan = "Laporan Data Pelanggan";
                jButtonPilihLaporan.setText("Pelanggan ▼");
            }
        });

        // 7. Masukkan Item ke dalam Popup
        popup.add(item1);
        popup.add(item2);
        popup.add(new javax.swing.JSeparator()); // Garis pemisah
        popup.add(item3);
        popup.add(item4);

        // 8. TAMPILKAN MENU (Di bawah tombol)
        popup.show(jButtonPilihLaporan, 0, jButtonPilihLaporan.getHeight());
    }//GEN-LAST:event_jButtonPilihLaporanActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonPilihLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
